testStabLineProg: stabbingLines.h readPoints.o readLines.o printLineByCoords.o\
getStabbedLines.o

readPoints.o : stabbingLines.h readPoints.cpp
g++ - std = c++17 -c readPoints.cpp -I.

readLines.o : stabbingLines.h readLines.cpp
g++ - std = c++17 -c readLines.cpp -I.

printLineByCoords.o : stabbingLines.h printLineByCoords.cpp
g++ - std = c++17 -c printLinebyCoords.cpp -I.

getStabbedLines.o : stabbingLines.h getStabbedLines.cpp
g++ - std = c++17 -c getStabbedLines.cpp -I.


